name: CSExpansion
main: com.chromaclypse.shopeditor.ShopPlugin
version: ${project.version}
description: Edit shop signs
author: ezeiger92
api-version: 1.13
depend: [ChromaLib, ChestShop]
commands:
  shopeditor:
    description: Open editor gui
    usage: /<command>
    permission: shopeditor.edit
    aliases: []
permissions:
  shopeditor.edit:
    description: Editor perm
    default: op
  shopeditor.salesmenu:
    description: Use buy/sell gui
    default: false
  shopeditor.any:
    description: Edit any shop
    default: op
